### ISSUE TITLE
Diagnostics delayed by 1 keystroke 

### ISSUE THREAD

**Issue by rzgry** [eclipse/lsp4jakarta#26]
Diagnostics added by https://github.com/MicroShed/jakarta-ls/pull/23 are always 1 keystroke behind.

**Comment by kathrynkodama** [comment]
The compilation unit being resolved here: https://github.com/MicroShed/jakarta-ls/blob/master/jakarta-eclipse/src/org/jakarta/jdt/JDTUtils.java#L111 is one keystroke behind the current document.

This results in an empty diagnostics list:  https://github.com/MicroShed/jakarta-ls/blob/master/jakarta-eclipse/src/org/jakarta/jdt/JDTServicesManager.java#L51-L53

**Comment by PENGYUXIONG** [comment]
I dont have much progress on this bug still. 

My thought is that, either 
https://github.com/MicroShed/jakarta-ls/blob/26641efb51a3fbd0e2f05118d0d4f1548395418d/jakarta-eclipse/src/org/jakarta/jdt/JDTUtils.java#L117

is returning incorrect Ifile which I am not sure how to verify

or it can possibly be `JavaCore.createCompilationUnitFrom(resource);` from
https://github.com/MicroShed/jakarta-ls/blob/26641efb51a3fbd0e2f05118d0d4f1548395418d/jakarta-eclipse/src/org/jakarta/jdt/JDTUtils.java#L125  is not behave properly

**Comment by kathrynkodama** [comment]
Adding the following to https://github.com/MicroShed/jakarta-ls/blob/master/jakarta.ls/src/main/java/io/microshed/jakartals/JakartaLanguageServer.java#L41 will update diagnostics on save: 
```
serverCapabilities.setTextDocumentSync(TextDocumentSyncKind.Incremental);
```
Keystroke delay still exists without saving

**Comment by tiganov** [comment]
Adding a delay before `createCompilationUnitFrom` is called [in JDTUtils.java](https://github.com/eclipse/lsp4jakarta/blob/26641efb51a3fbd0e2f05118d0d4f1548395418d/jakarta-eclipse/src/org/jakarta/jdt/JDTUtils.java#L125) seems to resolve the keystroke delay, but I'm not quite sure why, yet.

```java
try {
    Thread.sleep(1000);
} catch (InterruptedException e) {
    e.printStackTrace();
}
return JavaCore.createCompilationUnitFrom(resource);
```

**Comment by kathrynkodama** [comment]
Closed with #201
